@testset "Segregating sites" begin

    S = [dna"aatcga", dna"aaa", dna"tatcg", dna"catcgac", dna"aatc"]
    @test count(Segregating, S)[1] == 2 && count(Segregating, S)[2] == 3

    S = [dna"ATAATAAAAAAATAATAAAAAAATAAAAAAAATAAAAAAAA",
         dna"AAAAAAAATAAATAATAAAAAAATAAAAAAAAAAAAAAAAA",
         dna"AAAATAAAAATATAATAAAAAAATATAAAAAAAAAAAAAAA",
         dna"AAAAAAAAAAAATAATAAAAAAATAAATAAATAAAAAAAAA",
         dna"AAAATAAAAAAAATATAAAAAAATAAAAAAAAAAAAAAAAA",
         dna"AAAATAAAAAAAAAATAAAAAAAAAAAAAAAAAAATAAAAA",
         dna"AAAAAATAAAAATAATAAAAAAATAAAAAAAAAAAAAAAAA",
         dna"AAAAAAAAAAAAAAATAAAAAAATAAAAAAAAAAAAAAATA",
         dna"AAAAAAAAAAAAAAAAAAAAAAATAAAAAAAAAAAAAAAAA",
         dna"AAAAAAAAAAAAAAATAAAAAAATAATAAAAAAAAAAAAAA"]
    @test count(Segregating, S)[1] == 16 && count(Segregating, S)[2] == 41

end
